[build]
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."keep-alive"]
  included_files = ["netlify/functions/keep-alive.js"]

[functions."health"]
  included_files = ["netlify/functions/health.js"]

[functions."send-email"]
  included_files = ["netlify/functions/send-email.js"]
